### ISSUE TITLE
Tabs feature misses last steps on how to use with Antora

### ISSUE THREAD

**Issue by Adito5393** [couchbase/docs-ui#194]
Thanks for sharing this awesome UI. The tabs feature is very nice, but it took me too long to figure out how to use it. That last bit that is missing from the `README.md`, something among the lines:
- add the config to the antora playbook yml:

```yml
asciidoc:
  extensions:
  - '@asciidoctor/tabs'
# Optional attributes that can be config
  attributes:
    tabs: tabs
    tabs-sync-option: ''
```

- make sure the `package.json` contains the dependency:
```json
{
  "dependencies": {
    "@asciidoctor/tabs": "^1.0.0-beta.6"
  }
}
```

Would you like me to open a PR with the info?
However, if you find it redundant info, feel free to close the issue, no hard feelings :)
